# Generated by Django 5.2.1 on 2025-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_service_car_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото'),
        ),
    ]
