# Generated by Django 3.2.25 on 2025-05-30 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0004_maexam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maexam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterField(
            model_name='maexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='maexam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='maexam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название экзамена'),
        ),
        migrations.AlterField(
            model_name='maexam',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
